dataset_path: data

experiment: fast_dev
seed: null
save_epoch: 1
sanity_steps: 1
max_epoch: 250
scheduler: null
val_check_percent: 1.0
val_check_interval: 1
resume: null

num_mapping_layers: 2
lr_g: 0.002
lr_d: 0.00235
lazy_gradient_penalty_interval: 16
lazy_path_penalty_after: 1000000000
lazy_path_penalty_interval: 4
latent_dim: 512
lambda_gp: 0.0256
rgb_coef: 0.1
lpips_coef: 1
lambda_plp: 2
ada_start_p: 0.  #to disable set to -1
ada_target: 0.6
ada_interval: 4
ada_fixed: False
generator: stylegan2
use_simi_loss: True
mimin_layers: [0, 1, 2]
offset_weight: 5.0
simi_lambda: 1.0
use_mgd_loss: True
mgd_layers: [0, 1, 2]
mgd_lambda: 0.5

image_size: 32
num_eval_images: 8096
num_vis_images: 1024
batch_size: 64
batch_gpu: null
num_workers: 8

wandb_main: False
suffix: ''

hydra:
  output_subdir: null # Disable saving of config files. We'll do that ourselves.
  run:
    dir: .
